name: Variable Scope Demo

on:
  push:
    branches:
      - main

env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"

jobs:
  demo-scope:
    runs-on: ubuntu-latest

    env:
      MY_JOB_VARIABLE: "This is a job-level variable"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print workflow and job variables
        run: |
          echo "Workflow-level: $MY_WORKFLOW_VARIABLE"
          echo "Job-level: $MY_JOB_VARIABLE"

      - name: Step with step-level variable
        env:
          MY_STEP_VARIABLE: "This is a step-level variable"
        run: |
          echo "Workflow-level: $MY_WORKFLOW_VARIABLE"
          echo "Job-level: $MY_JOB_VARIABLE"
          echo "Step-level: $MY_STEP_VARIABLE"
